/*
 * Copyright (c) The mlkem-native project authors
 * Copyright (c) The mldsa-native project authors
 * SPDX-License-Identifier: Apache-2.0 OR ISC OR MIT
 */

#include "../../../../common.h"

#if defined(MLD_FIPS202_ARMV81M_NEED_X1) && \
    !defined(MLD_CONFIG_MULTILEVEL_NO_SHARED)

#define mld_keccak_f1600_x1_armv7m_asm MLD_NAMESPACE(keccak_f1600_x1_armv7m_asm)
void mld_keccak_f1600_x1_armv7m_asm(uint64_t state[25], const uint32_t rc[49]);

#define mld_keccak_f1600_x1_state_xor_bytes_asm \
  MLD_NAMESPACE(keccak_f1600_x1_state_xor_bytes_asm)
void mld_keccak_f1600_x1_state_xor_bytes_asm(void *state, const uint8_t *data,
                                             unsigned offset, unsigned length);

#define mld_keccak_f1600_x1_state_extract_bytes_asm \
  MLD_NAMESPACE(keccak_f1600_x1_state_extract_bytes_asm)
void mld_keccak_f1600_x1_state_extract_bytes_asm(void *state, uint8_t *data,
                                                 unsigned offset,
                                                 unsigned length);

/* The Adomnicai x1 core consumes 24 bit-interleaved round constants followed
 * by a 0xff loop terminator. Keep this table private to this backend. */
static MLD_ALIGN const uint32_t mld_keccakf1600_round_constants_x1[49] = {
    0x00000001, 0x00000000, /* RC0 */
    0x00000000, 0x00000089, /* RC1 */
    0x00000000, 0x8000008b, /* RC2 */
    0x00000000, 0x80008080, /* RC3 */
    0x00000001, 0x0000008b, /* RC4 */
    0x00000001, 0x00008000, /* RC5 */
    0x00000001, 0x80008088, /* RC6 */
    0x00000001, 0x80000082, /* RC7 */
    0x00000000, 0x0000000b, /* RC8 */
    0x00000000, 0x0000000a, /* RC9 */
    0x00000001, 0x00008082, /* RC10 */
    0x00000000, 0x00008003, /* RC11 */
    0x00000001, 0x0000808b, /* RC12 */
    0x00000001, 0x8000000b, /* RC13 */
    0x00000001, 0x8000008a, /* RC14 */
    0x00000001, 0x80000081, /* RC15 */
    0x00000000, 0x80000081, /* RC16 */
    0x00000000, 0x80000008, /* RC17 */
    0x00000000, 0x00000083, /* RC18 */
    0x00000000, 0x80008003, /* RC19 */
    0x00000001, 0x80008088, /* RC20 */
    0x00000000, 0x80000088, /* RC21 */
    0x00000001, 0x00008000, /* RC22 */
    0x00000000, 0x80008082, /* RC23 */
    0x000000ff,             /* loop terminator */
};

#define mld_keccak_f1600_x1_native_impl \
  MLD_NAMESPACE(keccak_f1600_x1_native_impl)
int mld_keccak_f1600_x1_native_impl(uint64_t *state)
{
  /* The x1 native xor/extract hooks keep state bit-interleaved in-place. */
  mld_keccak_f1600_x1_armv7m_asm(state, mld_keccakf1600_round_constants_x1);
  return MLD_NATIVE_FUNC_SUCCESS;
}

#define mld_keccakf1600_xor_bytes_x1_native_impl \
  MLD_NAMESPACE(keccakf1600_xor_bytes_x1_native_impl)
int mld_keccakf1600_xor_bytes_x1_native_impl(uint64_t *state,
                                             const uint8_t *data,
                                             unsigned offset, unsigned length)
{
  mld_keccak_f1600_x1_state_xor_bytes_asm(state, data, offset, length);
  return MLD_NATIVE_FUNC_SUCCESS;
}

#define mld_keccakf1600_extract_bytes_x1_native_impl \
  MLD_NAMESPACE(keccakf1600_extract_bytes_x1_native_impl)
int mld_keccakf1600_extract_bytes_x1_native_impl(uint64_t *state, uint8_t *data,
                                                 unsigned offset,
                                                 unsigned length)
{
  mld_keccak_f1600_x1_state_extract_bytes_asm(state, data, offset, length);
  return MLD_NATIVE_FUNC_SUCCESS;
}

#else /* MLD_FIPS202_ARMV81M_NEED_X1 && !MLD_CONFIG_MULTILEVEL_NO_SHARED */

MLD_EMPTY_CU(keccak_f1600_x1_armv7m)

#endif /* !(MLD_FIPS202_ARMV81M_NEED_X1 && !MLD_CONFIG_MULTILEVEL_NO_SHARED) \
        */

/* To facilitate single-compilation-unit (SCU) builds, undefine all macros.
 * Don't modify by hand -- this is auto-generated by scripts/autogen. */
#undef mld_keccak_f1600_x1_armv7m_asm
#undef mld_keccak_f1600_x1_state_xor_bytes_asm
#undef mld_keccak_f1600_x1_state_extract_bytes_asm
/* Some macros are kept because they are also defined in a header. */
/* Keep: mld_keccak_f1600_x1_native_impl (mve_x1.h) */
/* Keep: mld_keccakf1600_xor_bytes_x1_native_impl (mve_x1.h) */
/* Keep: mld_keccakf1600_extract_bytes_x1_native_impl (mve_x1.h) */
