/*
 * Copyright (c) The mlkem-native project authors
 * Copyright (c) The mldsa-native project authors
 * SPDX-License-Identifier: Apache-2.0 OR ISC OR MIT
 */

#include "../../../../common.h"

#if defined(MLD_FIPS202_ARMV81M_NEED_X1) && \
    !defined(MLD_CONFIG_MULTILEVEL_NO_SHARED)

#include "fips202_native_armv81m_x1.h"

#define mld_keccak_f1600_x1_armv7m_asm MLD_NAMESPACE(keccak_f1600_x1_armv7m_asm)
void mld_keccak_f1600_x1_armv7m_asm(uint32_t state[50], const uint32_t rc[49]);

#define mld_keccak_f1600_x1_state_xor_bytes_asm \
  MLD_NAMESPACE(keccak_f1600_x1_state_xor_bytes_asm)
void mld_keccak_f1600_x1_state_xor_bytes_asm(void *state, const uint8_t *data,
                                             unsigned offset, unsigned length);

#define mld_keccak_f1600_x1_state_extract_bytes_asm \
  MLD_NAMESPACE(keccak_f1600_x1_state_extract_bytes_asm)
void mld_keccak_f1600_x1_state_extract_bytes_asm(void *state, uint8_t *data,
                                                 unsigned offset,
                                                 unsigned length);

#define mld_keccak_f1600_x1_native_impl \
  MLD_NAMESPACE(keccak_f1600_x1_native_impl)
MLD_INTERNAL_API
int mld_keccak_f1600_x1_native_impl(uint64_t *state)
{
  /* The x1 native xor/extract hooks keep state bit-interleaved in-place. */
  mld_keccak_f1600_x1_armv7m_asm((uint32_t *)state,
                                 mld_keccakf1600_round_constants_x1);
  return MLD_NATIVE_FUNC_SUCCESS;
}

#define mld_keccakf1600_xor_bytes_x1_native_impl \
  MLD_NAMESPACE(keccakf1600_xor_bytes_x1_native_impl)
MLD_INTERNAL_API
int mld_keccakf1600_xor_bytes_x1_native_impl(uint64_t *state,
                                             const uint8_t *data,
                                             unsigned offset, unsigned length)
{
  mld_keccak_f1600_x1_state_xor_bytes_asm(state, data, offset, length);
  return MLD_NATIVE_FUNC_SUCCESS;
}

#define mld_keccakf1600_extract_bytes_x1_native_impl \
  MLD_NAMESPACE(keccakf1600_extract_bytes_x1_native_impl)
MLD_INTERNAL_API
int mld_keccakf1600_extract_bytes_x1_native_impl(uint64_t *state, uint8_t *data,
                                                 unsigned offset,
                                                 unsigned length)
{
  mld_keccak_f1600_x1_state_extract_bytes_asm(state, data, offset, length);
  return MLD_NATIVE_FUNC_SUCCESS;
}

#else /* MLD_FIPS202_ARMV81M_NEED_X1 && !MLD_CONFIG_MULTILEVEL_NO_SHARED */

MLD_EMPTY_CU(keccak_f1600_x1_armv7m)

#endif /* !(MLD_FIPS202_ARMV81M_NEED_X1 && !MLD_CONFIG_MULTILEVEL_NO_SHARED) \
        */

/* To facilitate single-compilation-unit (SCU) builds, undefine all macros.
 * Don't modify by hand -- this is auto-generated by scripts/autogen. */
#undef mld_keccak_f1600_x1_armv7m_asm
#undef mld_keccak_f1600_x1_state_xor_bytes_asm
#undef mld_keccak_f1600_x1_state_extract_bytes_asm
/* Some macros are kept because they are also defined in a header. */
/* Keep: mld_keccak_f1600_x1_native_impl (mve_x1.h) */
/* Keep: mld_keccakf1600_xor_bytes_x1_native_impl (mve_x1.h) */
/* Keep: mld_keccakf1600_extract_bytes_x1_native_impl (mve_x1.h) */
